source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'TZChat' do
    use_frameworks!
    pod 'GoogleWebRTC', '~> 1.1'
    pod 'SocketRocket'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end